### ISSUE TITLE
Context-specific accept_keymap

### ISSUE THREAD

**Issue by tvquizphd** [codota/tabnine-nvim#10]
### What I observe

The key I configure with `accept_keymap` is only usable by tabnine, even if no suggestions are present.

### What I expect

I'd expect `tabnine-nvim` to only highjack <TAB> when suggestions are available. At the start of an empty line, `<TAB>` should behave as a tab (in my case, spaces via `vim.opt.expandtab = true`).

Other previously-supported plugins like [coc-tabnine](https://github.com/neoclide/coc-tabnine) seemed to be able to implement this feature without issue. Perhaps my configuration now is slightly different, but at the moment I'm not willing to reconfigure my setup to reproduce this.

### Steps to reproduce

In `~/.config/nvim/init.lua`:

```
require('tabnine').setup({
  disable_auto_comment=true,
  accept_keymap="<Tab>",
  dismiss_keymap = "<C-Tab>",
  debounce_ms = 300,
  suggestion_color = {gui = "#808080", cterm = 244}
})
```

**Comment by amirbilu** [comment]
Hi @tvquizphd 
Thanks for reaching out!

I must say - I'm almost not using Tabs - so I completely missed it!  
Promise to fix it early next week.

**Comment by amirbilu** [comment]
Oh yeah - I completely get it. Super annoying. Tried to make it work now to be honest - but it seems to be taking more than few minutes. So it will have to wait for next week. 

I'll get it working. No worries.

**Comment by amirbilu** [comment]
haha
well.. I just could not sleep knowing it's not working for you. I've just issued a PR https://github.com/codota/tabnine-nvim/pull/12

It still a bit quirky but works much better now. Let me know how is for you before I merge

**Comment by amirbilu** [comment]
Technically it's

  `use { '~/projects/tabnine-nvim', run = "./dl_binaries.sh" }`

But you can just use Packer's ` branch`
