### ISSUE TITLE
TabNine.zip not extracted

### ISSUE THREAD

**Issue by lopi-py** [codota/tabnine-nvim#102]
**Describe the bug**
When I run the build script I get TabNine.zip but nothing more.
![image](https://github.com/codota/tabnine-nvim/assets/70210066/7e076b3a-b460-462a-a0b6-90152372e484)
This causes the plugin to get stuck in "tabnine loading"
![image](https://github.com/codota/tabnine-nvim/assets/70210066/fc97c388-06db-4330-aab4-674784168906)

**To Reproduce**
Run the build script on Windows

**Expected behavior**
The zip file should be extracted and deleted

**Version Info:**
- OS: Windows 10 Pro
- Neovim version (`nvim -v`): NVIM v0.10.0-dev-699+gb74262a33

**Additional context**
If I unzip it, the plugin works fine

**Comment by aarondill** [comment]
Please ensure the script is up-to-date. This was an issue which we encountered before, and, if it's what I think it is, it should already be solved. 

Additionally, please provide the last few lines of the build script if you *are* up-to-date

**Comment by lopi-py** [comment]
I just downloaded the plugin today, so it's the latest version. With that being said, I don't think it's necessary to show the last lines from the build script, but I will do it anyway once I get to my computer

**Comment by jarmo** [comment]
I experience the same issue. Just today switched to nvim-qt from gvim and started to use vim-plug for the first time so everything should be very fresh.

**Comment by lopi-py** [comment]
@aarondill ok so here are the last lines, exactly as the last ones from the last commit here:
```ps1
$targets | foreach-object {
    $target = $_
    $path = "$version/$target"

    if (!(test-path -path "binaries/$version/$target")) { New-Item -Path "binaries/$version/$target" -ItemType Directory -force | out-null }

    Write-Output "downloading $path"    
    invoke-webrequest -uri "$TABNINE_UPDATE_SERVICE/bundles/$path/TabNine.zip" -outfile "binaries/$path/TabNine.zip"
    # Stop this iteration if the download failed
    if ($LastExitCode -ne 0) {return}

    expand-archive "binaries/$path/TabNine.zip" "binaries/$path" 

    remove-item -path "binaries/$path/TabNine.zip"
}
```

**Comment by aarondill** [comment]
Thank you @lopi-py. Would you mind testing #103 to see if it fixes your issue?

**Comment by lopi-py** [comment]
Yes, it fixes it, but the plugin keeps saying "tabnine loading" until I reestart neovim, although this may be a separate issue

**Comment by aarondill** [comment]
@lopi-py if you call `require("tabnine").setup()` again, that should fix the status.
You could also call `require('tabnine.status').setup()`, but that's an internal call, so just use it as a one time fix.

**Comment by aarondill** [comment]
that would be a separate issue, as we only check if the binaries exist when we first startup, but I'd imagine that having the user restart their editor would have better performance than continuously checking if the file has now been created (globbing each time)
