### ISSUE TITLE
Tabnine Activation without web browser

### ISSUE THREAD

**Issue by tvquizphd** [codota/tabnine-nvim#105]
**Is your feature request related to a problem? Please describe.**
I can't resolve how to run `:TabnineHub` on my headless home server.

**Describe the solution you'd like**
Configuration of Tabnine username and password, even in a simple insecure way.

**Describe alternatives you've considered**
**edit**: I will attempt to set up [Brow.sh](https://brow.sh) in my terminal, to allow authentication through`:TabnineHub`. I've considered setting up Selenium to execute the login to TabnineHub for me.

**Additional context**
Happy to provide if needed

**Comment by aarondill** [comment]
You can run `:TabnineHubUrl` to get the url without opening the browser. This still requires a browser so it doesn't fix the problem. Iirc, it's running a local server, so you can't access it from another device either.

**Comment by amirbilu** [comment]
Are you able to do ssh port-forward to the remote server? In this case `:TabnineHubUrl` can help

**Comment by amirbilu** [comment]
@tvquizphd can this be closed?

**Comment by amirbilu** [comment]
Closing for now. Feel free to reopen
