### ISSUE TITLE
popup some thing failed [BUG]

### ISSUE THREAD

**Issue by shalei6698** [codota/tabnine-nvim#107]
**Describe the bug**
When i editor file, some lua error popup, content:

   Error  Error executing vim.schedule lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'tbl_contains'
	...al/share/nvim/lazy/tabnine-nvim/lua/tabnine/features.lua:7: in function 'callback'
	...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:89: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

**To Reproduce**

open neovim, start insert and get surprise

**Version Info:**

- OS (try `cat /etc/os-release`): Macos
- Neovim version (`nvim -v`): 0.9.1
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): 4.5.28
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`): 

**Additional context**
as  a pro user, i have long time no see "tabnine pro" in status line
try :TabnineHub  to login with success response; back to neovim still show "tabnien starter"

**Comment by aarondill** [comment]
@amirbilu it seems that response.enabled_features can actually not exist (thusly nil), so this could be fixed with a simple of check after line 5 (before beginning the loop)

```lua
if not response or not response.enabled_features then return end
```
