### ISSUE TITLE
Error Message [BUG]

### ISSUE THREAD

**Issue by shalei6698** [codota/tabnine-nvim#111]
**Describe the bug**
when i input, nvim popup error message, content:
   Error  Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:89: Expected comma or object end but found T_END at character 2369
stack traceback:
	[C]: in function 'decode'
	...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:89: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
   Error  Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:88: attempt to index local 'callback' (a nil value)
stack traceback:
	...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:88: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

**To Reproduce**
1. write some code
2. error message pop up

**Version Info:**

- OS (try `cat /etc/os-release`): Macos
- Neovim version (`nvim -v`): 0.9.1
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): 4.5.28
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`):

**Comment by aarondill** [comment]
@amirbilu here's another issue with the JSON.

**Comment by amirbilu** [comment]
Hi @shalei6698 is this still happening ?

**Comment by amirbilu** [comment]
Closing this for now. Feel free to reopen.

**Comment by shalei6698** [comment]
Not found recently
