### ISSUE TITLE
Tabnine does not show error if unzip is not installed

### ISSUE THREAD

**Issue by golden-expiriensu** [codota/tabnine-nvim#112]
**Describe the bug**
If unzip is not installed then Tabnine is not able to run dl_binaries.sh, but no error thrown, just endless loading

**To Reproduce**

1. Delete unzip
2. Install tabnine to nvim as described in https://github.com/codota/tabnine-nvim#install
3. Try to :TabnineHub and :TabnineHubUrl
4. Get no response and no errors
5. Try to run dl_binaries.sh manually and get an error that unzip is not installed
6. Install unzip and run again
7. Tabnine log in works as expected

**Expected behavior**
Show an error that unzip is not found - try to install it with your package manager

**Version Info:**

- OS (try `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
- Neovim version (`nvim -v`):
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`):
4.5.28

**Additional context**
WSL

**Comment by aarondill** [comment]
What's your package manager? Does it forward error messages from the build step to the user?

**Comment by golden-expiriensu** [comment]
I use apt-get. After adding it to packer and adding settings to after/plugin/tabnine.lua I tried many times to run :TabnineHub(Url) and just nothing happens. I made sure packer sync and also have reloaded nvim but :TabnineHub just do nothing (from user perspective). I guess it tries to call dl_binaries.sh under the hood and silently fails because I did not have unzip in my WSL
![photo_2023-09-08_19-12-39](https://github.com/codota/tabnine-nvim/assets/83108115/2d78a4c5-7efa-4d48-9b09-b593f0bfd4ea)

**Comment by aarondill** [comment]
Oh, it doesn't call dl_binaries. You have to do that.

The fact that it's silent is a problem, which I've actually worked on #82, im just waiting for @amirbilu to approve it and merge

**Comment by aarondill** [comment]
Unzip is required to install it though, so you will have to install that yourself

**Comment by golden-expiriensu** [comment]
I guess you right. But if it is has to be done manually then maybe it makes sense to extend installation instructions? Because now it says that you don't have to call binaries by yourself (just sync packer and add setup), and I solved problem and managed to call binaries only by searching similar problems in GitHub issues

**Comment by aarondill** [comment]
Didn't catch that you were using packer. PackerSync will run it, but only when it has been updated. If it ran once and failed, it won't run again until it's been updated. I believe packer should show you the error message from the script, but if not, then the real bug here is that the editor doesn't tell you, which is what the above PR looks to fix.

**Comment by amirbilu** [comment]
Guys what's the status here?

**Comment by aarondill** [comment]
I think this issue is resolved, right @golden-expiriensu ?

**Comment by golden-expiriensu** [comment]
Yep, I will track issue  in the mentioned pr
