### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shalei6698** [codota/tabnine-nvim#119]
**Describe the bug**
Error message popup when go into markdow file, Content:

   Error  Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/status.lua:20: attempt to index local 'response' (a userdata value)
stack traceback:
	...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/status.lua:20: in function 'callback'
	...ocal/share/nvim/lazy/tabnine-nvim/lua/tabnine/binary.lua:89: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

**To Reproduce**
1. just open markdown file

**Expected behavior**
Check var type before access

**Version Info:**

- OS (try `cat /etc/os-release`): macos 
- Neovim version (`nvim -v`): 0.9.2
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`):.active	0.0.1	4.12.0	4.13.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`):4.13.0

**Additional context**

**Comment by aarondill** [comment]
@amirbilu from `:h vim.json.decode`

```
    {opts} is a table with the key `luanil = { object: bool, array: bool }`
    that controls whether `null` in JSON objects or arrays should be converted
    to Lua `nil` instead of `vim.NIL`.
```

I wonder if we're running into vim.NIL. Someone should try `type(vim.NIL)` and see what it is.

**Comment by aarondill** [comment]
Having tested this myself. `type(vim.NIL)` is `userdata` and trying to index it does return this error.
