### ISSUE TITLE
[BUG/DOCS] Build command for PowerShell doesn't work as described in README

### ISSUE THREAD

**Issue by daephx** [codota/tabnine-nvim#121]
The README suggests using the command `pwsh.exe -file .\dl_binaries.ps1` on windows, but the script doesn't appear to be compatible with powershell 6+ (pwsh-core). Resulting in the following error.

```
if ((Get-WmiObject win32_operatingsystem | Select-Object osarchitectu …
      ~~~~~~~~~~~~~
The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
```

> Get-WmiObject have been deprecated in PowerShell Core. Please use CIM cmdlets.

The simplest solution is to change the README to use `powershell.exe`, otherwise the script should be updated.

**Comment by amirbilu** [comment]
@aarondill do you have time to take a  look?

**Comment by aarondill** [comment]
@amirbilu it seems like we can just replace `Get-WmiObject` with `Get-CimInstance`:

https://github.com/PowerShell/PowerShell/issues/4766

This is untested though.

**Comment by aarondill** [comment]
According to this https://github.com/dotnet/msbuild/issues/7329

I believe we can replace the entire check with just
`[System.Environment]::Is64BitProcess`

**Comment by daephx** [comment]
PowerShell 7 is my preference but as far as I know, windows still ships with the older PowerShell 5.1.
So, using something that's not back-compatible makes the install process more of a pain.

Could wrap with a version condition:

```powershell
if ($PSVersionTable.PSVersion.Major -ge 6) { Get-CimInstance }
else { Get-Get-WmiObject }
```

But `[System.Environment]::Is64BitProcess` seems pretty nice.
