### ISSUE TITLE
[Bug] Incorrect syntax

### ISSUE THREAD

**Issue by nmbs-adam-miller** [codota/tabnine-nvim#122]
This:
https://github.com/codota/tabnine-nvim/blob/2c06b4865415701dc638549032824664e114ee23/lua/tabnine/auto_commands.lua#L20

Should be this:
`api.nvim_create_autocmd({ "VimEnter", "ColorScheme" }, {`

**Comment by amirbilu** [comment]
Merged. Thanks guys
