### ISSUE TITLE
Possible bug in auto_commands.lua

### ISSUE THREAD

**Issue by mbainter** [codota/tabnine-nvim#123]
After upgrading today I began getting an odd error for TabNine. I am not certain, but I believe this `nvim_create_autocommand` call [here](https://github.com/codota/tabnine-nvim/blob/2c06b4865415701dc638549032824664e114ee23/lua/tabnine/auto_commands.lua#L20):

```lua
	api.nvim_create_autocmd("VimEnter,ColorScheme", {
```

should be:

```lua
	api.nvim_create_autocmd({ "VimEnter" , "ColorScheme" }, {
```

**Comment by aarondill** [comment]
Thanks for pointing this out and providing details. This has already been reported at #122 and should hopefully be fixed soon.

**Comment by mbainter** [comment]
Hah! I searched the issues for the function name and both events trying to see if someone else had reported it.  I guess we must've been writing them at the same time.
