### ISSUE TITLE
:TabnineHub not functional

### ISSUE THREAD

**Issue by raelldottin** [codota/tabnine-nvim#13]
I set up the Tabnine nvim plugin on macOS Ventura 13.1 using a MacBook Pro with an arm64 processor, and the TabnineHub command doesn't work.

Here is my configuration:

`use({ "codota/tabnine-nvim", run = "./dl_binaries.sh" })

-- import tabnine plugin safely
local status, tabnine = pcall(require, "tabnine")
if not status then
  return
end

tabnine.setup({
  disable_auto_comment = true,
  accept_keymap = "<Tab>",
  dismiss_keymap = "<C-]>",
  debounce_ms = 300,
  suggestion_color = { gui = "#808080", cterm = 244 },
  execlude_filetypes = { "TelescopePrompt" },
})`

Could someone help me out?

**Comment by amirbilu** [comment]
Hi @raelldottin 
Anything under `:messages`?
What is the output of `ps -ef | grep TabNine`? While nvim is running?

**Comment by raelldottin** [comment]
`pf -ef | grep TabNine | pbcopy`

Output:
  501 18946 23417   0  2:05PM ttys005    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox TabNine

**Comment by amirbilu** [comment]
What do you see under `tabnine-nvim/binaries` dir?

**Comment by raelldottin** [comment]
`.
├── .git
│   ├── FETCH_HEAD
│   ├── HEAD
│   ├── ORIG_HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   └── update.sample
│   ├── index
│   ├── info
│   │   └── exclude
│   ├── logs
│   │   ├── HEAD
│   │   └── refs
│   │       ├── heads
│   │       │   └── master
│   │       └── remotes
│   │           └── origin
│   │               └── HEAD
│   ├── modules
│   │   └── lua
│   │       └── tabnine
│   │           └── third_party
│   │               └── semver
│   │                   ├── HEAD
│   │                   ├── config
│   │                   ├── description
│   │                   ├── hooks
│   │                   │   ├── applypatch-msg.sample
│   │                   │   ├── commit-msg.sample
│   │                   │   ├── fsmonitor-watchman.sample
│   │                   │   ├── post-update.sample
│   │                   │   ├── pre-applypatch.sample
│   │                   │   ├── pre-commit.sample
│   │                   │   ├── pre-merge-commit.sample
│   │                   │   ├── pre-push.sample
│   │                   │   ├── pre-rebase.sample
│   │                   │   ├── pre-receive.sample
│   │                   │   ├── prepare-commit-msg.sample
│   │                   │   ├── push-to-checkout.sample
│   │                   │   └── update.sample
│   │                   ├── index
│   │                   ├── info
│   │                   │   └── exclude
│   │                   ├── logs
│   │                   │   ├── HEAD
│   │                   │   └── refs
│   │                   │       ├── heads
│   │                   │       │   └── master
│   │                   │       └── remotes
│   │                   │           └── origin
│   │                   │               └── HEAD
│   │                   ├── objects
│   │                   │   ├── info
│   │                   │   └── pack
│   │                   │       ├── pack-82967ec77b2e0a5d8253d582eb699ecc665fe541.idx
│   │                   │       └── pack-82967ec77b2e0a5d8253d582eb699ecc665fe541.pack
│   │                   ├── packed-refs
│   │                   └── refs
│   │                       ├── heads
│   │                       │   └── master
│   │                       ├── remotes
│   │                       │   └── origin
│   │                       │       └── HEAD
│   │                       └── tags
│   ├── objects
│   │   ├── info
│   │   └── pack
│   │       ├── pack-6573d45be04495f9ac993ab26ee7c0d448611da4.idx
│   │       └── pack-6573d45be04495f9ac993ab26ee7c0d448611da4.pack
│   ├── packed-refs
│   ├── refs
│   │   ├── heads
│   │   │   └── master
│   │   ├── remotes
│   │   │   └── origin
│   │   │       └── HEAD
│   │   └── tags
│   └── shallow
├── .gitignore
├── .gitmodules
├── .luarc.json
├── README.md
├── dl_binaries.sh
├── expamples
│   ├── javascript.gif
│   ├── javascript.js
│   └── python.py
└── lua
    ├── lualine
    │   └── components
    │       └── tabnine.lua
    ├── tabnine
    │   ├── binary.lua
    │   ├── third_party
    │   │   └── semver
    │   │       ├── .git
    │   │       ├── .travis.yml
    │   │       ├── MIT-LICENSE.txt
    │   │       ├── README.md
    │   │       ├── rockspecs
    │   │       │   ├── semver-1.1.0-1.rockspec
    │   │       │   ├── semver-1.1.1-1.rockspec
    │   │       │   ├── semver-1.2.0-1.rockspec
    │   │       │   └── semver-1.2.1-1.rockspec
    │   │       ├── semver.lua
    │   │       └── spec
    │   │           ├── custom_assertions.lua
    │   │           └── semver_spec.lua
    │   └── utils.lua
    └── tabnine.lua

46 directories, 78 files`

**Comment by raelldottin** [comment]
![Screenshot 2023-01-11 at 2 22 03 PM](https://user-images.githubusercontent.com/317015/211898633-7840eba3-8256-412e-b080-de5444c846f9.png)
 Ok, I have some progress. I had to disable my VPN.

**Comment by raelldottin** [comment]
Is there anything else I should test before I start celebrating?

![Screenshot 2023-01-11 at 2 23 30 PM](https://user-images.githubusercontent.com/317015/211898900-674d173e-57c1-4bfc-b431-a1c526c76a36.png)
![Screenshot 2023-01-11 at 2 23 52 PM](https://user-images.githubusercontent.com/317015/211898986-94e99b04-50e9-4d02-8a72-3cbd93490644.png)

**Comment by amirbilu** [comment]
Whoo hoo 🎉
Are you getting completions?

**Comment by raelldottin** [comment]
Yes, I'm getting completions. 👍 

![Screenshot 2023-01-11 at 2 28 24 PM](https://user-images.githubusercontent.com/317015/211899906-5f0d3615-88b8-4d35-b391-fc3ae28a299b.png)

**Comment by danielo515** [comment]
I also had to manually run the download script. However, despite the lualine integration was working tabnine was disabled. I had to run PackerCompile to make this start working, so anyone reading this, be aware.
