### ISSUE TITLE
[FEATURE] Look for binary on path, or allow users to provide their own binary

### ISSUE THREAD

**Issue by JonathanLorimer** [codota/tabnine-nvim#130]
I would like to provide the tabnine binary myself. It would be great if the nvim plugin checked for an existing binary or allowed the user to provide a path in the config.

**Comment by amirbilu** [comment]
Hi @JonathanLorimer this definitely possible..what is your usecase though?

**Comment by JonathanLorimer** [comment]
@amirbilu I'd like to provide the binary instead of using a third party download script

**Comment by amirbilu** [comment]
Hi @JonathanLorimer saw your issue in the other repo. While this is quite simple to implement.. i'm afraid I don't have time for it at the moment. Meanwhile.. you can just hardcode your path here https://github.com/codota/tabnine-nvim/blob/6ec8cdc58899491518f11fb2e3009d593c23e710/lua/tabnine/binary.lua#L64

Amir

**Comment by amirbilu** [comment]
closing for now
