### ISSUE TITLE
attempt to index local 'response' (a nil value)

### ISSUE THREAD

**Issue by nmbs-adam-miller** [codota/tabnine-nvim#138]
I'm getting the error mentioned in the title on this line occasionally. Without knowing what the binary is doing...would it be appropriate to have some sort of nil check here?

https://github.com/codota/tabnine-nvim/blob/086f843c45e86358232b6e9b43d6f87379a7763b/lua/tabnine/status.lua#L20

**Comment by amirbilu** [comment]
Hi @nmbs-adam-miller I hope this https://github.com/codota/tabnine-nvim/commit/23be7c6c79405af52f290e58051d128e7f609a1d fixes this. Keep me posted.
