### ISSUE TITLE
Windows support - comment/vote here if you need it

### ISSUE THREAD

**Issue by amirbilu** [codota/tabnine-nvim#14]
If there's a demand - I'll make the effort to make the plugin works on Windows

**Comment by Harsh04Gautam** [comment]
Thank you for providing this , it works on WSL. I tried it. i had to manually run the .sh file but after that it is working fine. only issue is whenever there is a lsp suggestion, the suggestion by the tabnine gets removed.

**Comment by amirbilu** [comment]
Yes. This is by design as Tab is common key for completion navigation + it conflicts with cmp virtual text. You can comment out this part if you're interested in having them both together.

See https://github.com/codota/tabnine-nvim/issues/6

**Comment by Achill113** [comment]
Seems to work with WSL, as mentioned above; however, I cannot get TabnineHub to open to activate my Pro utilities.

**Comment by amirbilu** [comment]
Hi @Achill113
TabnineHub relies on `$BROWSER` env 
Make sure to set it's pointing to your browser

**Comment by Achill113** [comment]
@amirbilu thank you, that was it. I appreciate your quick response ❤️

**Comment by instance-id** [comment]
I have native Windows support working. I am going to make a PR here shortly once I get things cleaned up and add some documentation for it.
