### ISSUE TITLE
[BUG] Deprecated in neovim 0.10 of the `vim.lsp.buf.server_ready()` function

### ISSUE THREAD

**Issue by zeroday0619** [codota/tabnine-nvim#140]
**Describe the bug**

Deprecated in neovim 0.10 of the `vim.lsp.buf.server_ready()` function, resulting in a deprecated alarm.

https://neovim.io/doc/user/deprecated.html#vim.lsp.buf.server_ready()

The function in question is used in this code:
https://github.com/codota/tabnine-nvim/blob/master/lua/tabnine/chat/codelens.lua#L32C31-L32C31

**Version Info:**

- OS (try `cat /etc/os-release`): Ubuntu 22.04.3 LTS
- Neovim version (`nvim -v`): NVIM v0.10.0-dev
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): .active  0.0.1  4.73.0  4.75.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`): 4.75.0

**Comment by amirbilu** [comment]
@zeroday0619 thanks!
I will try to get to it next week

**Comment by amirbilu** [comment]
@aarondill maybe got time for this?
