### ISSUE TITLE
What does the "tabnine" virtual text do?

### ISSUE THREAD

**Issue by bfulop** [codota/tabnine-nvim#146]
Hello,

I've been trying out Tabnine in Neovim, so far it works great, including the chat feature!

Sometimes I see the _Tabnine_ virtual text appear next to my code **even in Normal mode**. I was wondering about its signification?

![BalintFulop 2024-01-22--14-48-31](https://github.com/codota/tabnine-nvim/assets/1718128/8e593b63-bdc8-417e-862f-f708127d7f5c)

Thank you!

**Comment by amirbilu** [comment]
Hi @bfulop great question. I understand the ux around it is not great. This means you can ask Tabnine Chat about this scope, using `:TabnineExplain` `:TabnineFix` etc..

![image](https://github.com/codota/tabnine-nvim/assets/7681048/229787f7-f157-46ed-b419-6bef608fe5a6)

**Comment by bfulop** [comment]
Thanks for the clarification!

Actually it did made me intuitively open the chat and apply the suggested fixes! 
So after all the _tabnine hint_ did work as intended. I just wasn't 100% sure about its purpose.
I will now be paying more attention to it and see what improvements it suggests.
