### ISSUE TITLE
[FEATURE] WSL Support

### ISSUE THREAD

**Issue by feoh** [codota/tabnine-nvim#148]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use TabNine on Neovim working in WSL. It's LInux, so this shouldn't be too heavy a lift if at all.

**Describe the solution you'd like**
I realize this could be construed as an edge case, I'd be happy for even a way to do a more manual setup process.

Right now though :TabNineHub does nothing and neither does :TabNineUrl

I can download and run the binaries and even log into tab9 from the browser with the binaries I get from running './download_binaries.sh" though!

**Describe alternatives you've considered**

I could run the native Windows Neovim from within WSL.

**Comment by amirbilu** [comment]
Hi @feoh did you try `:TabnineLoginWithAuthToken` ? does it work for you?

**Comment by feoh** [comment]
Nothing happens just like all the other Tabnine subcommands on WSL.

Between this and a persistent dialog on my Mac screaming that Apple can't check the Tabnine binaries for malicious software, I'm sad to say I've given up on Tabnine and am using Github Copilot, so I'll close this issue as I won't be much good for debugging help going forward.

Thanks for the kind response!
