### ISSUE TITLE
[FEATURE] Allow manual completion via function

### ISSUE THREAD

**Issue by Guergeiro** [codota/tabnine-nvim#149]
**Is your feature request related to a problem? Please describe.**
When using this plugin, it is recommended that we map the `accept_key` to something that doesn't collide with other plugin mappings. While this works, it would be interesting if we can do a manual complete ourselves by using some kind of provided function. Generally, autocomplete engines provide ways of doing this ([asyncomple.vim](https://github.com/prabirshrestha/asyncomplete.vim/blob/master/doc/asyncomplete.txt#L129), [ddc.vim](https://github.com/Shougo/ddc.vim/blob/main/doc/ddc.txt#L531), [ncm2](https://github.com/ncm2/ncm2/blob/master/doc/ncm2.txt#L413), [CoC](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L2203), [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L247) etc).

**Describe the solution you'd like**
I'm going to type vimscript since I don't know how to do it in lua in neovim (migrating atm):
```vim
inoremap <silent> <expr> <cr>
    \ tabnine#has_suggestion() ?
    \ tabnine#confirm() : '<cr>'

```
**Describe alternatives you've considered**
The only alternative I've considered is having some function as `accept_key` that we can have logic attached to it that decides whether or not we want to return a valid keybind or just `nil`.

**Additional context**
Although this plugin doesn't serve as a autocomplete plugin, it very much has autocomplete functionality. Having an API that allows us to inspect the results of this plugin could even benefit other users of it; [cmp-tabnine](https://github.com/tzachar/cmp-tabnine) comes to mind.

**Comment by aarondill** [comment]
i've had a pr waiting over 10 months over at #70 to implement this exact feature! i'd really appreciate your feedback on that pr if you have any

**Comment by Guergeiro** [comment]
> i've had a pr waiting over 10 months over at #70 to implement this exact feature! i'd really appreciate your feedback on that pr if you have any

Glancing over it with my limited lua knowledge, it seems that you went with the alternative suggestion described in my issue. It seems like it should work, although personally I'd rather have the functions exposed by *tabnine-vim* like described above (or equivalents).

Will probably use your fork if no further development is made on this issue.

**Comment by aarondill** [comment]
the original goal of my pr was to implement it with as small of a diff as possible.

if I get a go ahead from @amirbilu, I would also prefer to have separate `has_completion` and `complete` functions

**Comment by aarondill** [comment]
@Guergeiro amir has given his approval for me to go ahead and make these changes!
I plan to add this interface:
```lua
require("tabnine").accept_suggestion() -- return boolean - success (?) else no return - NOTE: no error if no suggestion!
require("tabnine").has_suggestion() -- return boolean - has
require("tabnine").dismiss_suggestion() -- see above for accept_suggestion
```

do you have any feedback on this api? would this work for your use case?

**Comment by aarondill** [comment]
secondly, do you think it makes more sense to expose these under `require'tabnine'` or `require'tabnine.keymaps'`? I haven't decided and amir doesn't seem to have an opinion either way. As a potential user of this API, i'd like to see what's most intuitive to you.

**Comment by amirbilu** [comment]
We're already exposing `require('tabnine.status').status()` .. so I would go with `tabnine.keymaps`

**Comment by Guergeiro** [comment]
The functions provided seem nice. Where should they be namespaced to, is a matter for the maintainers of the package, but from personal opinion, `keymaps` doesn't particularly sit well with me.

Since this is a neovim plugin, why don't you look into how nvim-cmp does this?

**Comment by aarondill** [comment]
@Guergeiro nvim-cmp does this:
```lua
cmp.mapping = require('cmp.config.mapping')
```
which is essentially namespacing it into `.mapping`

I think i'll stick with `tabnine.keymaps`, since that's what amir expressed is his preference

**Comment by Guergeiro** [comment]
I've just finished reading their doc.txt and they have it at top level with `cmp.visible`, `cmp.complete`, `cmp.abort`, `cmp.close`, etc.

I think you are mixing the functions that interact with tabnine with the keybinds that call these functions. The latter would make sense to be namespaced into something like `keybinds`.
