### ISSUE TITLE
[BUG] Tabnine does not give suggestion when there is no code written

### ISSUE THREAD

**Issue by Maduki-tech** [codota/tabnine-nvim#153]
**Describe the bug**
When I start writing my code. I expect it to show me some suggestions before I start typing. (Like in Github Copilot)

Also when I try to reproduce the Example in the GIF where you can write a comment and then it should autocomplete it with a suggestion, this suggestion never comes up for me

**To Reproduce**
let's say I have this function in Java:

```java
    public static void bubbleSort(int[] array) {
    }
```
I expected it to give me some hints on how to start with it.
1. I will create a new line in the function
2. I will wait for the suggestion to show.

Also if I give it some comments like
//Write me a bubble sort

it will not work

**Expected behavior**
I expect the suggestion to be shown.

**Version Info:**

- OS: macOS 14.2.1 23C71 arm64
- kernel: 23.2.0
- Neovim version (`nvim -v`):
NVIM v0.10.0-dev-1999+g6f6abd8c0
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377

- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): 4.116.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`): do not have this file also not listed with ls -a

**Comment by amirbilu** [comment]
Hi @Maduki-tech are you a Pro user? Did you log in? Please share a video of what you're experiencing

**Comment by Maduki-tech** [comment]
Hello @amirbilu 
Yes I'm a Pro user.
After a bit of Programming, it seems to work. (at least for the Java part) 

I work on a Lua Project, there it will not show the Autocomplete anymore

**Comment by amirbilu** [comment]
Please share a video/project Im using Tabnine for project :)
