### ISSUE TITLE
[BUG] Accepting multi-line suggestions doesn't move the cursor to the end of the suggested text

### ISSUE THREAD

**Issue by barrydevp** [codota/tabnine-nvim#155]
**Describe the bug**
Accepting multi-line suggestions doesn't move the cursor to the end of the suggested text.

**To Reproduce**

1. Write an instruction to produce multi-line suggestions
2. Accept it
3. The cursor is not in the right position

**Expected behavior**
The cursor will be moved to the end of the accepted text.

**Version Info:**

- OS (try `cat /etc/os-release`): macOS 12.7.2
- Neovim version (`nvim -v`): v0.10.0-dev-2533+g970b60aa7-Homebrew
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): 4.116.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`): 4.116.0

**Additional context**
I think there is a problem with this line https://github.com/codota/tabnine-nvim/blob/da893a988395c100c9656576656fcf18acd44bfc/lua/tabnine/completion.lua#L29 . It should be 
```
api.nvim_win_set_cursor(0, { fn.line(".") + #lines-1, fn.col(".") + #lines[#lines] })
```
I believe. I tested and it worked very well.

**Comment by aarondill** [comment]
that makes sense to me! can you create a PR with this change?

**Comment by barrydevp** [comment]
sure, I will

**Comment by amirbilu** [comment]
Can't believe I missed it. Thank you! Closing as fixed

**Comment by gachikuku** [comment]
Hello,
I don't know why, but for me it works fine.

https://github.com/codota/tabnine-nvim/assets/11743804/c0bcf42b-c245-4c54-9873-9b8a99c87d1a

**Comment by barrydevp** [comment]
@gachikuku I think it is due to the difference in the neovim version.

**Comment by aarondill** [comment]
@barrydevp can you post the full output of `nvim -v -V1` please

**Comment by barrydevp** [comment]
@aarondill here you are
```
NVIM v0.10.0-dev-2533+g970b60aa7-Homebrew
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-970b60a/share/nvim"

Run :checkhealth for more info
```

**Comment by aarondill** [comment]
@barrydevp could you add
`print("["..state.rendered_completion.."]")` to line 18 of `lua/tabnine/completion.lua` and show the results when accepting both a single line and a multiline completion?

**Comment by barrydevp** [comment]
@aarondill 
I think the problem is on the side of neovim api, as in this issue https://github.com/neovim/neovim/pull/24901. Copilot-nvim plugin also faced this problem before https://github.com/zbirenbaum/copilot.lua/issues/216.
But well, if you desired:
[![asciicast](https://asciinema.org/a/wTV5ikJA6SdfBOE9yYY60eHn1.svg)](https://asciinema.org/a/wTV5ikJA6SdfBOE9yYY60eHn1)

**Comment by aarondill** [comment]
@barrydevp that does look to be the issue.
I wonder if using `vim.api.nvim_put` instead with follow mode would avoid needing to move the cursor at all?

**Comment by barrydevp** [comment]
```diff
diff --git a/lua/tabnine/completion.lua b/lua/tabnine/completion.lua
index cb162a3..6d195b5 100644
--- a/lua/tabnine/completion.lua
+++ b/lua/tabnine/completion.lua
@@ -25,7 +25,7 @@ function M.accept()
                return
        end

-       api.nvim_buf_set_text(0, fn.line(".") - 1, fn.col(".") - 1, fn.line(".") - 1, fn.col(".") - 1, lines)
+       api.nvim_put(lines, "c", true, true)
        api.nvim_win_set_cursor(0, { fn.line("."), fn.col(".") + #lines[#lines] })
        state.completions_cache = nil
 end
```

@aarondill it works on my environment, both single and multi-line suggestions.
[![asciicast](https://asciinema.org/a/hOLWNn8Vt89kc4dtnNXymk4si.svg)](https://asciinema.org/a/hOLWNn8Vt89kc4dtnNXymk4si)

**Comment by aarondill** [comment]
@gachikuku does the above change work for you as well?

**Comment by gachikuku** [comment]
It works!

**Comment by aarondill** [comment]
Nice! @barrydevp, would you mind creating a pr with that diff?

**Comment by barrydevp** [comment]
@aarondill I've made a pull request #160
