### ISSUE TITLE
Problem with multi-line completion preview not receiving all lines or cutting it off

### ISSUE THREAD

**Issue by henryoliver** [codota/tabnine-nvim#16]
Probably something simple to solve, but for some reason, the preview for ML completion is cutting or not receiving more than ten lines. I'm a pro user at Tabnine, and all my configuration seems fine here; my LSP previews go beyond 10 lines:

![image](https://user-images.githubusercontent.com/870784/212416082-845e0834-daa8-4630-b51b-1cbd6db34444.png)

```
tabnine:setup({
    max_lines = 1000,
    max_num_results = 20,
    sort = true,
    run_on_every_keystroke = true,
    snippet_placeholder = " ",
    show_prediction_strength = true,
})
...
                if entry.source.name == "cmp_tabnine" then
                    local detail = (entry.completion_item.data or {}).detail

                    vim_item.kind = " "

                    if detail and detail:find(".*%%.*") then
                        vim_item.kind = vim_item.kind .. " " .. detail
                    end

                    if (entry.completion_item.data or {}).multiline then
                        vim_item.kind = vim_item.kind .. " " .. "[AI  - ML]"
                    end
                end

...
```

Appreciate any help here. Thanks!

**Comment by amirbilu** [comment]
Hi @henryoliver 
Note that you're using [cmp-tabnine](https://github.com/tzachar/cmp-tabnine).

Closing this for now. If you're having any questions - feel free to open another issue ( + you're welcome to try this plugin!)

**Comment by henryoliver** [comment]
Sorry about that! Thanks for replying!
