### ISSUE TITLE
Shadow text sticking around

### ISSUE THREAD

**Issue by bmalinconico** [codota/tabnine-nvim#17]
I'm unable to provide you with an exact production step, but I have encountered many situations where the shadow text stays around even as i'm moving around. It also ends up covering text instead of moving it around.

![image](https://user-images.githubusercontent.com/19909708/213212645-90d48df9-04b4-4243-b4e1-2b7f416c641a.png)

**Comment by amirbilu** [comment]
@bmalinconico thanks for submitting this!
Assumed to be duplicated of https://github.com/codota/tabnine-nvim/issues/22 . Feel free to follow there for updates.
