### ISSUE TITLE
[BUG] Warning in Neovim 0.11.x

### ISSUE THREAD

**Issue by davemackintosh** [codota/tabnine-nvim#173]
**Describe the bug**
Warnings when using inside of Neovim 0.11.x

```
vim.lsp.buf_get_clients() is deprecated, use vim.lsp.get_clients() instead. :help deprecated
Feature will be removed in Nvim 0.12
stack traceback:
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1092: in function 'buf_get_clients'
	...l/share/nvim/lazy/tabnine-nvim/lua/tabnine/workspace.lua:15: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**To Reproduce**

Install on Neovim 0.11.x

**Expected behavior**
No warnings

**Version Info:**

- OS (try `cat /etc/os-release`): Ubuntu 23.10 in WSL2
- Neovim version (`nvim -v`): 0.11.0
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`): 4.160.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`): no active directory found

**Additional context**

**Comment by amirbilu** [comment]
fixed by https://github.com/codota/tabnine-nvim/pull/170
