### ISSUE TITLE
[FEATURE] Supply auth_cmd

### ISSUE THREAD

**Issue by erichlf** [codota/tabnine-nvim#176]
**Is your feature request related to a problem? Please describe.**
My development environment is in docker containers and so every time I restart a docker container I have to re-authorize tabnine. It would be nice if there could be an automated way to authorize the tabnine plugin.

**Describe the solution you'd like**
Add the ability to supply an `auth_cmd` where the output of this command is a string containing the authorization token. I tend to store authorization tokens and api keys in gnu pass and so one possible command would be `pass show tabnine/auth_token`. But this command could be anything that results in a string that is the auth token.

**Describe alternatives you've considered**
I would consider most anything that makes it where I don't have to manually enter the auth token. However, solutions like storing in an environment variable should be avoided.

**Comment by amirbilu** [comment]
@erichlf are you referring to api keys given to old pro users?

**Comment by erichlf** [comment]
Sorry I mean AUTH Token.

**Comment by amirbilu** [comment]
The auth token lives for 1 hour so this won't work. What other plugins do?

**Comment by amirbilu** [comment]
A nice workaround could be to mount `~/.config/TabNine`. Assuming you're logged-in in the host

**Comment by erichlf** [comment]
That is good to know.

**Comment by amirbilu** [comment]
Does it work for you?

**Comment by erichlf** [comment]
I have to figure out why when I bind mount the directory, or use it as a volume it becomes owned by root and I don't have permissions to do anything with it.

**Comment by erichlf** [comment]
The issue is that `~/.config` doesn't already exist in the container and so when `~/.config/TabNine` is mounted it will then create the `~/.config` directory giving to root ownership, which then breaks all sorts of other things that I have going on that depends on that directory having non-root ownership. What I do as a workaround is that put the following in my `dotfiles` setup script:
```bash
if [[ -d $HOME/.config && ! $(stat -c "%U" $HOME/.config) == "$(whoami)" ]]; then
  sudo chown $(whoami):$(whoami) $HOME/.config 
fi
```

**Comment by amirbilu** [comment]
Closing this
