### ISSUE TITLE
Help in setup with Windows

### ISSUE THREAD

**Issue by 007interesting** [codota/tabnine-nvim#185]
I am experiencing issues logging into Tabnine with nvim using the nvchad config. Here’s how I’ve integrated Tabnine into my setup -

-> Updating init.lua and plugins.lua -

```init.lua
. . .
require("tabnine").setup {
  disable_auto_comment = true,
  accept_keymap = "<A-l>",
  dismiss_keymap = "<A-c>",
  debounce_ms = 800,
  suggestion_color = { gui = "#808080", cterm = 244 },
  exclude_filetypes = { "TelescopePrompt", "NvimTree" },
  log_file_path = nil, -- absolute path to Tabnine log file
  ignore_certificate_errors = false,
}
```

```plugins.lua
local plugins = {
    { "codota/tabnine-nvim", build = "pwsh.exe -file .\\dl_binaries.ps1" }
} 
return plugins
```

-> Restarted the nvim
-> [BUG] Running :TabnineHub did nothing
-> Attempted :TabnineLoginWithAuthToken, but it also resulted in no response

**Comment by amirbilu** [comment]
@aarondill can you assist?

**Comment by aarondill** [comment]
what nvim version are you using? `nvim -v -V1`
Is the build script running correctly? 
The plugin is *likely* installed into `~/AppData/Local/nvim/lazy/tabnine-nvim`.
what are the contents `$plugin/` and `$plugin/binaries/`, and the file `$plugin/binaries/.active`?


This is why we have the issue template. It isn't designed for windows, but the same information should've been collected before creating the issue.

**Comment by aarondill** [comment]
PS, @amirbilu should we use log_file_path for debug logs in the nvim plugin to make debugging easier? currently it's only used in the chat.

**Comment by 007interesting** [comment]
> what nvim version are you using? `nvim -v -V1` Is the build script running correctly? The plugin is _likely_ installed into `~/AppData/Local/nvim/lazy/tabnine-nvim`. what are the contents `$plugin/` and `$plugin/binaries/`, and the file `$plugin/binaries/.active`?
> 
> This is why we have the issue template. It isn't designed for windows, but the same information should've been collected before creating the issue.

**\>** nvim -v -V1
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

Yes the build script is running fine
**~/AppData\Local\nvim-data\lazy\tabnine-nvim>** pwsh.exe -file .\\dl_binaries.ps1
downloading 4.187.0/x86_64-pc-windows-gnu

**Contents**
![image](https://github.com/user-attachments/assets/f647f64e-3879-4d79-972c-38d5f8f99708)

I tried running Tabnine.exe, and it did nothing, got no response.

Thanks

**Comment by 007interesting** [comment]
> what nvim version are you using? `nvim -v -V1` Is the build script running correctly? The plugin is _likely_ installed into `~/AppData/Local/nvim/lazy/tabnine-nvim`. what are the contents `$plugin/` and `$plugin/binaries/`, and the file `$plugin/binaries/.active`?
> 
> This is why we have the issue template. It isn't designed for windows, but the same information should've been collected before creating the issue.

> what nvim version are you using? `nvim -v -V1` Is the build script running correctly? The plugin is _likely_ installed into `~/AppData/Local/nvim/lazy/tabnine-nvim`. what are the contents `$plugin/` and `$plugin/binaries/`, and the file `$plugin/binaries/.active`?
> 
> This is why we have the issue template. It isn't designed for windows, but the same information should've been collected before creating the issue.

**\>** nvim -v -V1
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

Yes the build script is running fine
**~/AppData\Local\nvim-data\lazy\tabnine-nvim>** pwsh.exe -file .\\dl_binaries.ps1
downloading 4.187.0/x86_64-pc-windows-gnu

**Contents**
![image](https://github.com/user-attachments/assets/f647f64e-3879-4d79-972c-38d5f8f99708)

I tried running Tabnine.exe, and it did nothing, got no response.

Thanks

**Comment by 007interesting** [comment]
@aarondill I tried manual registration with Tabnine.exe -

**.\binaries\4.187.0\x86_64-pc-windows-gnu\TabNine.exe --key <key>**
Activation failed: Error(ApiRequests(Error(ErrorParsingServerResponseAsJson { response_text: "Not Found", error: "expected value at line 1 column 1" }, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

**Comment by aarondill** [comment]
tabnine.exe isn't intended to be run manually, it requires specific input to stdin to actually do anything.
Can you confirm (using task manager, or similar programs) that when you open a file in neovim, tabnine.exe is running (and doesn't die immediately)?

**Comment by 007interesting** [comment]
Yes the tabnine is running fine
![Screenshot (1)](https://github.com/user-attachments/assets/aee170eb-7a58-4a46-ab03-7664a876827c)
