### ISSUE TITLE
tabnine only working after executing `:TabnineHub` in each nvim session

### ISSUE THREAD

**Issue by h4pZ** [codota/tabnine-nvim#19]
Hi, the plugin will only work after I have executed `:TabnineHub`. This means that every time I open nvim I need to call `:TabnineHub` for it to start suggesting completions after comments.

**Comment by amirbilu** [comment]
@h4pZ can you share your `init.lua`?

**Comment by h4pZ** [comment]
Yes, here it is https://github.com/h4pZ/nvim/blob/master/init.lua

Here is the packer installation https://github.com/h4pZ/nvim/blob/master/lua/user/plugins.lua#L159

and here the basic config that I call from the `init.lua` https://github.com/h4pZ/nvim/blob/master/lua/user/tabnine.lua

**Comment by h4pZ** [comment]
It is working now without me calling TabnineHub. Haven't change anything so far. Maybe it was an issue with the enterprise license being so new? 

I'm closing this as I can't replicate the issue anymore.
