### ISSUE TITLE
Conflict with Eslint Lsp

### ISSUE THREAD

**Issue by tuanha168** [codota/tabnine-nvim#20]
I really love this plugins, but i have some problem with other Lsp

I'm using Eslint Lsp ( install with Mason ) and it's still working normally until i tried install tabnine.
Tabnine working fine, but everytime i move cursor or enter insert mode it's showing like this.
![image](https://user-images.githubusercontent.com/71129995/214605093-d6dbf7b2-4b42-4d68-95c4-3277a00a2fcb.png)
And Eslint is complete broken, no code diagnostic and no code actions.
Other Lsp ( typescript, python, sumneko_lua ) are working normally.

Please let me know if this is Eslint's problem or any other things i can help to fix this. Thanks!!

**Comment by amirbilu** [comment]
Hi @tuanha168 please share you `init.lua`. I'm working with eslint on daily basis with no issues

**Comment by amirbilu** [comment]
Closing this as stale. Feel free to reopen if needed.

**Comment by tuanha168** [comment]
@amirbilu 
Hi, sorry I was busy lately.
I'm using NvChad as my config and I have this repo as the custom folder (for NvChad's customization)
https://github.com/tuanha168/nvim/tree/nvchad

And this is my lsp config file with eslint
https://github.com/tuanha168/nvim/blob/nvchad/config/lspconfig.lua

Now after I update eslint LSP, the error prompt is gone, eslint lsp is still running and attached to the buffer, but have no effect ( no code diagnose, code action, .... )
