### ISSUE TITLE
Feature: Enable and disable commands

### ISSUE THREAD

**Issue by jb0000** [codota/tabnine-nvim#25]
Hi, 

this plugin is amazing and works very well so far. 
It would be great if it would offer commands to enable and disable it manually. Sometimes when just doing quick edits, the suggestions are distracting. The [copilot vim plugin](https://github.com/github/copilot.vim/blob/release/doc/copilot.txt) offers similar commands and could be a great example here. 

Thank you for putting so much effort in this nvim plugin!

**Comment by amirbilu** [comment]
@jb0000 Appreciate this. Will add this to the backlog.

**Comment by amirbilu** [comment]
https://github.com/codota/tabnine-nvim/pull/59 adds this. Many thanks to @aarondill for initiating this
