### ISSUE TITLE
Where do I put the Basic configuration activation?

### ISSUE THREAD

**Issue by lerner-zhang** [codota/tabnine-nvim#27]
I am new to Neovim and don't know where to put [this configuration](https://github.com/codota/tabnine-nvim#:~:text=Basic%20configuration%20activation). I tried to put it in ~/.config/nvim/init.vim, but some errors occurred.

**Comment by amirbilu** [comment]
Welcome to Neovim :)
This is a lua code. Meaning it has to be either in `init.lua`, or in `init.vim` inside lua block. i.e

```
lua << EOF
// configuration here
EOF
```

**Comment by lerner-zhang** [comment]
Great to know that. Thanks.
