### ISSUE TITLE
Cannot accept after pressing Tab

### ISSUE THREAD

**Issue by lerner-zhang** [codota/tabnine-nvim#28]
I installed YouCompleteMe and nvim-cmp, and the tab key lost its effect. 
I tried: 
1. paste the activation configuration after loading YouCompleteMe, intending to overlay the mapping
2. I changed the accept_keymap: `accept_keymap="<S-Tab>"`

**Comment by amirbilu** [comment]
Hi @lerner-zhang please share your configuration

**Comment by lerner-zhang** [comment]
In `~/.config/nvim/init.vim`: 
```
inoremap jj <esc>

call plug#begin()
  Plug 'tpope/vim-commentary'  
  Plug 'https://github.com/Valloric/YouCompleteMe'
  Plug 'preservim/vim-markdown'
  Plug 'pangloss/vim-javascript'
  Plug 'scrooloose/nerdtree'
  Plug 'tpope/vim-fugitive'
  Plug 'davidhalter/jedi-vim'

  Plug 'neovim/nvim-lspconfig'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-cmdline'
  Plug 'hrsh7th/nvim-cmp'
  
  " For vsnip users.
  Plug 'hrsh7th/cmp-vsnip'
  Plug 'hrsh7th/vim-vsnip'
  
  " For luasnip users.
  " Plug 'L3MON4D3/LuaSnip'
  " Plug 'saadparwaiz1/cmp_luasnip'
  
  " For ultisnips users.
  " Plug 'SirVer/ultisnips'
  " Plug 'quangnguyen30192/cmp-nvim-ultisnips'
  
  " For snippy users.
  " Plug 'dcampos/nvim-snippy'
  " Plug 'dcampos/cmp-snippy'
call plug#end()

nnoremap <C-n> :NERDTreeToggle<CR>
let g:NERDTreeWinPos = "right"

set completeopt=menu,menuone,noselect
lua require('config')
```

And the following in `~/.config/nvim/lua/config.lua`: 
https://github.com/hrsh7th/nvim-cmp#recommended-configuration

**Comment by amirbilu** [comment]
On a side note.. `YouCompleteMe` and `nvim-cmp` provide the same functionality. It's probably not a good idea to have them both running together

**Comment by lerner-zhang** [comment]
> Hi @lerner-zhang it seems like YouCompleteMe indeed maps `<Tab>` and `<S-Tab>`, see here: https://github.com/ycm-core/YouCompleteMe/blob/50379d35ddc38ee3651f568d080442d5e4cb4a3a/plugin/youcompleteme.vim#LL114-L118C75
> 
> A possible solution would be to map those to other keys.. for example:
> 
> ```viml
> let g:ycm_key_list_select_completion = ['<C-j>']
> let g:ycm_key_list_previous_completion =  ['<C-k>']
> ```

I appended these two lines in `~/.config/nvim/init.vim` but no magic happens.

**Comment by lerner-zhang** [comment]
> On a side note.. `YouCompleteMe` and `nvim-cmp` provide the same functionality. It's probably not a good idea to have them both running together

Thanks! I just forgot to delete the plugins I tried and failed after finding that YCM worked for me.

**Comment by amirbilu** [comment]
@lerner-zhang are you able to navigate using `<C-j>` / `<C-k>` ?

**Comment by lerner-zhang** [comment]
Now `<C-j>` and `<C-k>` work for YCM, but `<Tab>` still does not work.

**Comment by amirbilu** [comment]
Silly question maybe - did you set `accept_keymap="<Tab>"`?

**Comment by lerner-zhang** [comment]
Here is the `~/.config/nvim/lua/config.lua`: 
```{lua}
require("user.plugins")

require('tabnine').setup({
  disable_auto_comment=true,
  accept_keymap="Enter",
  dismiss_keymap = "<C-]>",
  debounce_ms = 800,
  suggestion_color = {gui = "#808080", cterm = 244},
  execlude_filetypes = {"TelescopePrompt"}
})

require("packer").startup({
  function(use)
    use "your/plugin"
  end,

  config = {
    package_root = "~/.vim/nvim-plugged"
  }
})
```

By the way, I want to move all source code of plugin from `/Users/lernerzhang/.local/share/nvim/plugge` to `~/.vim/nvim-plugged`, and I wonder if this config is right: 

```
require("packer").startup({
  function(use)
    use "your/plugin"
    -- the above line should be wrong I think
  end,

  config = {
    package_root = "~/.vim/nvim-plugged"
  }
})
```

**Comment by amirbilu** [comment]
Great! Closing this
