### ISSUE TITLE
Screenshots in the readme of your github.

### ISSUE THREAD

**Issue by Pakrohk** [codota/tabnine-nvim#29]
Never feel this is spam.
I'm trying to help make your git page a little better.
Currently, almost everyone uses tabnine along with plugins like [cmp](https://github.com/tzachar/cmp-tabnine) or [coc](https://github.com/neoclide/coc-tabnine) and there are beautiful configurations for it. Please replace the gif in redme with more modern configurations.
(I use tabnine by default in [nvpak](https://github.com/pakrohk-dotfiles/nvpak), it can also be activated manually in [lunarvim ](https://github.com/LunarVim/LunarVim)and [nvchad](https://github.com/NvChad/NvChad))

**Comment by amirbilu** [comment]
Not sure I understand the requirement. Can you please elaborate further more? This plugin is not related to cmp or coc

**Comment by amirbilu** [comment]
Closing this for now. Feel free to reopen.
