### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by crusj** [codota/tabnine-nvim#3]
macos13
neovim0.8.
nvim-cmp.

Nothing happened, I tried many languages
<img width="486" alt="image" src="https://user-images.githubusercontent.com/20185895/206820976-b59e038c-e49b-4efd-bcad-6d9d5f21c5a5.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/20185895/206821027-97306c77-8639-4f7f-aff2-5404606925ab.png">
Excute `:TabnineHub` , nothing happens.

**Comment by psilospore** [comment]
I also didn't see anything on :TabnineHub. What mistake did you make?

**Comment by GlowSquid** [comment]
I would also like to know. :TabnineHub gives no feedback whatsoever. I code through a server, so it would be cool to get a link in the log since no browser windows open up.

**Comment by GlowSquid** [comment]
Works after setting it up on a local machine, then copying the contents of ~/.config/TabNine to the remote server.
