### ISSUE TITLE
Typo?! execlude_filetypes 

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [codota/tabnine-nvim#30]
I guess `exclude_filetypes` was meant?!

**Comment by ipsod** [comment]
There's also a directory in the root folder called "expamples".  Lol.  Makes me wonder about the state of the actual code.

**Comment by amirbilu** [comment]
Typos. Thanks. Will fix this. The code is awesome by the way, you're welcome to take a look :)

**Comment by amirbilu** [comment]
merged, thank you!
