### ISSUE TITLE
plugin stopped working

### ISSUE THREAD

**Issue by ipsod** [codota/tabnine-nvim#33]
Hi.  I'm not sure what happened, but a week or two ago the plugin stopped working for me.  `TabnineHub` no longer launches the website (but also doesn't give any error), and suggestions/completions are never shown.

I can't figure out any way to get error messages or any output at all out of the plugin, to diagnose or troubleshoot it.

**Comment by ipsod** [comment]
I tried installing it with a fresh install of LazyVim, and still have the same thing happening.

Did I install wrongly?  The install itself seemed to work, though the plugin is totally unresponsive.

To install the plugin, I created this file at `lua/plugins/tabnine.lua`, and LazyVim did the rest after a restart:

``` lua
return {
  {
    "codota/tabnine-nvim",
    run = "./dl_binaries.sh",
    config = function()
      require("tabnine").setup({
        disable_auto_comment = true,
        accept_keymap = "<Tab>",
        dismiss_keymap = "<C-]>",
        debounce_ms = 800,
        suggestion_color = { gui = "#808080", cterm = 244 },
        exclude_filetypes = { "TelescopePrompt" },
      })
    end,
  },
}

```

**Comment by amirbilu** [comment]
Hi @ipsod
Promise to look at this tomorrow

**Comment by amirbilu** [comment]
Hi @ipsod .. can you run `tree  .` inside `tabnine-nvim` dir and share the output?
plus if you can run `ps -ef | grep TabNine` while `nvim` is running and share the output?

**Comment by ipsod** [comment]
Sure, and thanks!

```
➜  tabnine-nvim git:(master) tree
.
├── dl_binaries.sh
├── examples
│   ├── javascript.gif
│   ├── javascript.js
│   └── python.py
├── lua
│   ├── lualine
│   │   └── components
│   │       └── tabnine.lua
│   ├── tabnine
│   │   ├── auto_commands.lua
│   │   ├── binary.lua
│   │   ├── completion.lua
│   │   ├── config.lua
│   │   ├── consts.lua
│   │   ├── keymaps.lua
│   │   ├── state.lua
│   │   ├── third_party
│   │   │   └── semver
│   │   │       ├── MIT-LICENSE.txt
│   │   │       ├── README.md
│   │   │       ├── rockspecs
│   │   │       │   ├── semver-1.1.0-1.rockspec
│   │   │       │   ├── semver-1.1.1-1.rockspec
│   │   │       │   ├── semver-1.2.0-1.rockspec
│   │   │       │   └── semver-1.2.1-1.rockspec
│   │   │       ├── semver.lua
│   │   │       └── spec
│   │   │           ├── custom_assertions.lua
│   │   │           └── semver_spec.lua
│   │   ├── user_commands.lua
│   │   └── utils.lua
│   └── tabnine.lua
└── README.md

9 directories, 25 files
```

```
➜  ~ ps -ef | grep TabNine
ipsod      113275  113222  0 10:19 pts/1    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox TabNine
```

**Comment by amirbilu** [comment]
It looks like `dl_binaries.sh` didn't run. Care to run it manually?

**Comment by ipsod** [comment]
Yes, that fixed it.   Does it look like my install script is incorrect?  Or, maybe something else going on?

**Comment by amirbilu** [comment]
To be honest.. I have no experience with lazy

**Comment by ipsod** [comment]
I had the same thing happen when using LunarVim, which uses Packer.  I actually only installed LazyVim to see if I could get this plugin to work.

Probably just user-error.  I don't understand lua or how neovim configs work in any depth.

Thanks for the help.

**Comment by amirbilu** [comment]
Appreciate it. Closing this if this okay. Feel free to reopen

**Comment by aarondill** [comment]
`run` should be `build` in Lazy.nvim. Run is unique to packer. @ipsod
