### ISSUE TITLE
esc will accept tabnine's recommendation

### ISSUE THREAD

**Issue by ruinb0w** [codota/tabnine-nvim#36]
When I tap `esc`, Neovim will accept Tabnine's recommendation, but I set the keymap as `<C-[>`

tabnine config
```
lua <<EOF
require('tabnine').setup({
  disable_auto_comment=true, 
  accept_keymap="<C-[>",
  dismiss_keymap = "<C-]>",
  debounce_ms = 800,
  suggestion_color = {gui = "#808080", cterm = 244},
  exclude_filetypes = {"TelescopePrompt"}
})
EOF
```

**Comment by ruinb0w** [comment]
it's my neovim configuration `https://github.com/ruinb0w/my-vim-config`

**Comment by amirbilu** [comment]
Hi @ruinb0w
See `:help <Esc>`

![image](https://user-images.githubusercontent.com/7681048/224532528-26d8f4d1-230b-4839-9db1-2328711927bc.png)

`<Esc>` & `<C-[>` are equivalent. You will have to choose a different key binding.

**Comment by ruinb0w** [comment]
> Hi @ruinb0w See `:help <Esc>`
> 
> ![image](https://user-images.githubusercontent.com/7681048/224532528-26d8f4d1-230b-4839-9db1-2328711927bc.png)
> 
> `<Esc>` & `<C-[>` are equivalent. You will have to choose a different key binding.

Tank you for your answer and sorry for bother you.

**Comment by amirbilu** [comment]
All good. Closing this for now. Happy coding!
