### ISSUE TITLE
Windows Setup

### ISSUE THREAD

**Issue by stefhol** [codota/tabnine-nvim#38]
Hi I had some problems with the setup in windows

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.2
dl_binaries.ps1
I cannot find any reference for 
`expand-archive -path "binaries/$path/TabNine.zip" -outputpath "binaries/$path"` as I read it it should always be 
`expand-archive -path "binaries/$path/TabNine.zip" -destinationpath "binaries/$path" `
also you can just drop options to just 
`expand-archive "binaries/$path/TabNine.zip" "binaries/$path" `

On my machine I have Powershell 7 and $PSVersionTable.PSEdition is "Core" so this script is not working

Also the build sripts needs a execution policy so it can run. So for example 
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`

And lastly if the binaries are not there, tabnine is not providing a error message and updating in lazy does not trigger a new build of the binaries.

With the proposed changes tabnine  is working on my machine

**Comment by amirbilu** [comment]
Closing this as resolved
