### ISSUE TITLE
Stuck on tabnine loading

### ISSUE THREAD

**Issue by rootex-** [codota/tabnine-nvim#40]
Hi, thanks for your creation.

Configured as in README.md on my Mac.  
What could be the possible issue?  

Lualine shows only this:
<img width="179" alt="Screenshot 2023-03-23 at 19 09 00" src="https://user-images.githubusercontent.com/8237030/227265223-972788fd-dd86-41dc-9182-c5f967a9017c.png">

I've tried both commands TabnineHub and TabnineHubUrl, they do nothing.

**Comment by amirbilu** [comment]
Try to follow this thread
https://github.com/codota/tabnine-nvim/issues/33

If the issue still persists - let me know

**Comment by rootex-** [comment]
Thanks, I forgot to mention that tabnine had successfully started on my Lazy.nvim managed config, but it didn't want to run on a Packer managed config

**Comment by amirbilu** [comment]
Hi @rootex-  did manage to get this working? If not.. please share your configuration

**Comment by rootex-** [comment]
Hi @amirbilu, I don't know how but the Packer-based config started working today without any actions from my side  👀 Now it shows 'tabnine starter' and both commands function. 
I really don't have any idea how and why it started working. 
I think you can close the issue, thanks for your help 🤝

**Comment by amirbilu** [comment]
Cool. Let me know should you have any further questions
