### ISSUE TITLE
Suggestions are added after dismissed on empty lines

### ISSUE THREAD

**Issue by piedrahitapablo** [codota/tabnine-nvim#41]
First of all thanks for writing this plugin.

I'm struggling to use the plugin with the default key bindings because when I'm on an empty line and want to add some tabs for spacing the suggestions are always added, even if I dismiss them. 

In the following gif you can see the issue:

![ezgif-4-f1549b12a3](https://user-images.githubusercontent.com/6783539/227576758-7acc3d9a-b8a7-40a7-ad5b-e3c48b13e0f1.gif)

Is this expected? Is there a way to disable the extension in these cases?

**Comment by amirbilu** [comment]
Hi @piedrahitapablo  - thanks for reaching out!
Sounds like a bug. Will try to look at this next week.

**Comment by amirbilu** [comment]
https://github.com/codota/tabnine-nvim/pull/42 should fix this

**Comment by piedrahitapablo** [comment]
Thanks @amirbilu, just tested and it's fixed
