### ISSUE TITLE
Sometimes the suggestion hides the remaining characters of the line

### ISSUE THREAD

**Issue by piedrahitapablo** [codota/tabnine-nvim#43]
Hi, I'm not sure if this is expected, a bug or something that's caused by nvim itself, but I found out that sometimes the tabnine suggestion shadows the remaining characters of the line as it's shown on this gif:

![ezgif-5-e810c7fc4a](https://user-images.githubusercontent.com/6783539/228343246-62b946a0-bd15-4263-9f4e-fc7cc679273a.gif)

Also, I think this happens inside parenthesis, I haven't been able to reproduce it in any other cases.

I don't know a lot about lua or nvim plugins, but I can help and make a PR if needed.

Thanks!

**Comment by hungnguyen3** [comment]
I also encountered this issue.
