### ISSUE TITLE
[Feature] Avoid download of *all* binaries on install.

### ISSUE THREAD

**Issue by aarondill** [codota/tabnine-nvim#52]
When installing the plugin, and on every update, it installs all the available binaries (ie `x86_64-apple-darwin`, `x86_64-unknown-linux-musl`, and `aarch64-apple-darwin`) when I need only the linux one. Perhaps `dl_binaries.sh` could take a flag/set of flags for which binary to install, or else auto detect the current infrastructure to install only the needed binaries.
In the best case scenario, I envision a combination of both above attempts, where it attempts to detect infrastructure, but on fail, falls back to downloading all three available binaries. It could also take a flag to force installation of only one given binary (skipping infrastructure detection if present)
This would work something like this:
```console
> ./dl_binaries.sh
Auto Detect Infrastructure
> ./dl_binaries.sh 
Detection failed - Installing all binaries
> ./dl_binaries.sh --x86_64-linux ( OR fully qualified --x86_64-unknown-linux-musl )
Installs only that one binary
> # MAYBE - Is there ever a use for this?
> ./dl_binaries.sh --x86_64-linux --x86_64-apple-darwin 
Installing both
```
In case it wasn't obvious, the output above is just for demonstration and I would not necessarily expect the script to output any of these messages (Although perhaps `Auto-detecting infrastructure` / `Detection failed - Installing all binaries` might be useful for debugging purposes)
An additional option would be to take positional arguments instead of a flag, and is really just the preference of the maintainers.
This would save storage, as well as decreasing startup time on an update.

**Comment by amirbilu** [comment]
Hi @aarondill  thanks for reaching out!
This is just me being lazy. You're welcome to issue a PR! btw, [cmp-tabnine install script](https://github.com/tzachar/cmp-tabnine/blob/main/install.sh) is doing it
