### ISSUE TITLE
[Question] Is there a "Next" and "Prev" suggestion keymap like VSCode version?

### ISSUE THREAD

**Issue by jackblackevo** [codota/tabnine-nvim#56]
<img width="648" src="https://user-images.githubusercontent.com/15699333/230031693-b966cc5f-9c98-4743-8dc3-7f7ce17489e4.png">

Hi, does TabNine for Neovim have a "Next" and "Prev" suggestion keymap similar to that in VSCode?

**Comment by aarondill** [comment]
These don't yet exist, however, if you'd like to see them added, I'd suggest you go over to #21 and upvote it (thumbs up), perhaps leave a comment explaining when you find these helpful and how often you use it!
-- Not a member of the Tabnine team

**Comment by amirbilu** [comment]
What @aarondill said :)

**Comment by amirbilu** [comment]
Closing this for now.
