### ISSUE TITLE
[Feature] Command to see TabnineStatus

### ISSUE THREAD

**Issue by czuma** [codota/tabnine-nvim#57]
Will be great to add a command like :TabnineStatus
with a response like: Tabnine pro ready to help
or: Oops Tabnine is not running...

**Comment by amirbilu** [comment]
Hi @czuma you can get the status with the lualine integration.
I agree a command would be helpful too. Would add this next week

**Comment by czuma** [comment]
Sure but i'm for example are using NvChad and don't have lualine, probably i'm too noob to remove the actual statusbar and replace it with lualine but will try.

**Comment by amirbilu** [comment]
https://github.com/codota/tabnine-nvim/pull/59 introduces `:TabnineStatus` command.
On a side note -  you can customize `NVchad` to introduce this on this on the status line (using `require('tabnine.status').status()`

https://nvchad.com/docs/config/nvchad_ui
