### ISSUE TITLE
lazyvim pressing <Tab> wont work, but after remapping it will work

### ISSUE THREAD

**Issue by bryant-video** [codota/tabnine-nvim#58]
Im using lazyvim, the ide layer. and this is my config
```
return {
  {
    "codota/tabnine-nvim",
    config = function()
      require("tabnine").setup({
        disable_auto_comment = true,
        accept_keymap = "<Tab>",
        dismiss_keymap = "<C-]>",
        debounce_ms = 300,
        suggestion_color = { gui = "#808080", cterm = 244 },
        execlude_filetypes = { "TelescopePrompt" },
      })
    end,
  },
}
```
Tab wont work, it will just increase indentation. But if i remap it to sth else like `<C-t>`, it will work, i really dont know why.
Btw, i do have nvim-cmp enabled, but it doesnt have any shortcuts mapped to Tab

**Comment by amirbilu** [comment]
I'm not familiar with `lazyvim`, but cmp definitely maps `<Tab>`. This line from my own config  may help 
https://github.com/amirbilu/nvim-config/blob/3bb7edbad67d0d08aa56cf2dca5ceaa6886ffbd6/lua/bilu/plugins/lsp-zero.lua#L16
