### ISSUE TITLE
[Question] Support for aarch64 linux

### ISSUE THREAD

**Issue by ShaunMWallace** [codota/tabnine-nvim#61]
Currently using fedora 37 (aarch64) in Parallels on an M1 mac. Based on the install script, it appears Darwin aarch64 is supported but not Linux. Any plans to add support?

**Comment by amirbilu** [comment]
Hi @ShaunMWallace appreciate you reaching out. Unfortunately supporting aarch64 is not on the roadmap at the moment. Promise to update here when it does. Closing this for now.
