### ISSUE TITLE
Repeated errors

### ISSUE THREAD

**Issue by pgib** [codota/tabnine-nvim#62]
I had this happen the other day out of the blue, and updating my plug-in resolved it. But this morning it started happening again without any changes to my environment.

Any thoughts what could cause this? It makes things unusable because it keeps repeating the error in Neovim.

```
Error executing vim.schedule lua callback: ...patrick/.vim/plugged/tabnine-nvim/lua/tabnine/binary.lua:75: Expected object key string but found unexpected end of string at character 8193
stack traceback:
        [C]: in function 'decode'
        ...patrick/.vim/plugged/tabnine-nvim/lua/tabnine/binary.lua:75: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...patrick/.vim/plugged/tabnine-nvim/lua/tabnine/binary.lua:74: attempt to index local 'callback' (a nil value)
stack traceback:
        ...patrick/.vim/plugged/tabnine-nvim/lua/tabnine/binary.lua:74: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Comment by aarondill** [comment]
`callback.callback(vim.json.decode(line))` - line 75
This is the line that the error pointed to. I'm guessing the binary is returning non-json values.
Try this command:
 `rm -r ~/.vim/plugged/tabnine-nvim/binaries/ && ~/.vim/plugged/tabnine-nvim/dl_binaries.sh`
That will remove the binaries that are installed and download them

**Comment by aarondill** [comment]
> `callback.callback(vim.json.decode(line))` - line 75 This is the line that the error pointed to. I'm guessing the binary is returning non-json values. Try this command: `cd ~/.vim/plugged/tabnine-nvim/ && ./dl_binaries.sh` That will remove the binaries that are installed and download them

Updating would have done this automattically, which is why it likely fixed your issues before

**Comment by amirbilu** [comment]
Hi @pgib. Thanks for reaching out and apologies on that bad experience.
Please share your configuration

**Comment by amirbilu** [comment]
In the meantime - I've just added a new `log_file_path` configuration key. (see https://github.com/codota/tabnine-nvim/pull/63)

If you can please turn on logs and send them  to `support@tabnine.com` once you're experiencing this issue.

Make sure to mention this ticket.

Appreciate it - and once again - sorry for the inconvenience

**Comment by pgib** [comment]
@amirbilu Thanks so much for that! I have updated and configured the `log_file_path`. If it happens again, I'll hopefully have some more useful information.

I'm using Neovim 0.8.3 on an Apple Silicon Mac running macOS 13.3.

**Comment by aarondill** [comment]
> @amirbilu Thanks so much for that! I have updated and configured the `log_file_path`. If it happens again, I'll hopefully have some more useful information.
> 
> I'm using Neovim 0.8.3 on an Apple Silicon Mac running macOS 13.3.

To be clear, did redownloading the binaries fix the issue (even if temporarily)?

**Comment by pgib** [comment]
> > @amirbilu Thanks so much for that! I have updated and configured the `log_file_path`. If it happens again, I'll hopefully have some more useful information.
> > I'm using Neovim 0.8.3 on an Apple Silicon Mac running macOS 13.3.
> 
> To be clear, did redownloading the binaries fix the issue (even if temporarily)?

It did, but doing a `:PlugUpdate` did not. (Guessing the `do` handler is only triggered if there are newer commits.)

**Comment by amirbilu** [comment]
Guys, can this be closed?

**Comment by aarondill** [comment]
Redownloading the binaries resolved his problem, so I'd say close it, and if @pgib has the issue again, he can reopen it or create a new one.

**Comment by amirbilu** [comment]
Okay. Closing for now
