### ISSUE TITLE
use tar instead of unzip

### ISSUE THREAD

**Issue by sauterp** [codota/tabnine-nvim#68]
I installed tabnine-nvim with vim Plug following all the instructions in the README. 
It got stuck in `tabnine loading` after :PlugInstall. I found the reason why when I ran `dl_binaries.sh` myself:

```
~/.local/share/nvim/plugged/tabnine-nvim$ ./dl_binaries.sh
downloading 4.4.284/x86_64-apple-darwin
./dl_binaries.sh: 19: unzip: not found
```

You shouldn't assume that unzip is always available on Linux systems(or BSD etc.). I suggest that you switch your distribution of binaries to tarballs and use tar. AFAIK tar is much more ubiquitous, it's even available on windows.

*also it's not cool to download binaries for darwin on a Linux system, I'll never use these binaries so they are wasting space on my drive.

**Comment by aarondill** [comment]
see #53 for the last bit, we're working on it

**Comment by aarondill** [comment]
as for the rest of it, I don't speak for the Tabnine team, but I would guess that since their distribution is already public, too many scripts and apps rely on it being a zip (such as tzachar/cmp-tabnine) and so this change would not be possible.

Perhaps a check in the install script that `unzip` is installed (with a friendly error message if not) and/or a mention in the readme that you need to have `unzip` included would be a good addition.

**Comment by amirbilu** [comment]
https://github.com/codota/tabnine-nvim/pull/53 will be merged soon

As for the zip.. this indeed has long history and probably won't be changed anytime soon. Most of the plugins download and unzip the the binaries using their own API. In this case using bash was easier (over using luazip for example).

This might be changed sometimes later on. As a first aid we can add a note in the readme + show a nicer message.

**Comment by aarondill** [comment]
> #53 will be merged soon
> 
> As for the zip.. this indeed has long history and probably won't be changed anytime soon. Most of the plugins download and unzip the the binaries using their own API. In this case using bash was easier (over using luazip for example).
> 
> This might be changed sometimes later on. As a first aid we can add a note in the readme + show a nicer message.

I'd like to work on that message. Would you like me to edit on master or #53? 53 changes enough that it's almost guaranteed to create a conflict, so if it's certain to be merged, I'd prefer to avoid the merge conflict later on.

**Comment by amirbilu** [comment]
Go ahead @aarondill

**Comment by amirbilu** [comment]
I mean, go ahead with editing #53

**Comment by amirbilu** [comment]
Closing this
