### ISSUE TITLE
Sometimes the completion doesn't clear while in normal mode

### ISSUE THREAD

**Issue by aarondill** [codota/tabnine-nvim#74]
I'm not certain what circumstances lead to it, but recently i've been encountering the issue where completions won't be cleared while i'm in normal mode and the only way to fix it is to go insert mode, and leave insert mode again, so i'd like to propose we add an autocmd for CursorMoved to clear the completion. (May have to check not insert mode to avoid breaking the CursorMovedI aucmd)

```lua 
api.nvim_create_autocmd("CursorMoved", { pattern = "*", callback = function()
if not -- ( vim.isInsert something here???) 
then completion.clear() end
end })
```

**Comment by amirbilu** [comment]
The code should be able to clear completions when switching modes but I know it misses sometimes. We can either try figure why this is not working (might be hard to debug) or use something similar to your suggestion

**Comment by aarondill** [comment]
from the nvim help docs for autocmds: 

```
InsertLeave
Just after leaving Insert mode.  Also when using CTRL-O i_CTRL-O.  But not for i_CTRL-C.
```

so, at least one case that can't be prevented is ctrl+c to exit insert mode. I don't think this is causing my issue, especially since ctrl+c is remapped for me, but it's still a point of failure for the InsertLeave event

**Comment by amirbilu** [comment]
I used to use `ModeChanged` and it hasn't been working good as well
