### ISSUE TITLE
Error likely causes in `keymaps.lua`

### ISSUE THREAD

**Issue by Yang-Kyle** [codota/tabnine-nvim#78]
I use `vim-plug` and `init.vim`.
I just add the required content and reported this under the **Nvim** lastest `v0.6.1`.

> E5108: Error executing lua .../share/nvim/plugged/tabnine-nvim/lua/tabnine/keymaps.lua:9: attempt to index field 'keymap' (a nil value)
stack traceback:
        .../share/nvim/plugged/tabnine-nvim/lua/tabnine/keymaps.lua:9: in function 'setup'
        ...t/.local/share/nvim/plugged/tabnine-nvim/lua/tabnine.lua:12: in function 'setup'
        [string ":lua"]:10: in main chunk

I'm not familiar with Lua, but I think it seems wrong in `~/.local/share/nvim/plugged/tabnine-nvim/lua/tabnine/keymaps.lua`.
it is the content.
```lua
local M = {}
local state = require("tabnine.state")
local config = require("tabnine.config")
local completion = require("tabnine.completion")

function M.setup()
        local accept_keymap = config.get_config().accept_keymap
        local dismiss_keymap = config.get_config().dismiss_keymap
        vim.keymap.set("i", accept_keymap, function()
                if not state.completions_cache then
                        return accept_keymap
                end
                vim.schedule(completion.accept)
        end, { expr = true })

        vim.keymap.set("i", dismiss_keymap, function()
                if not state.completions_cache then
                        return dismiss_keymap
                end
                vim.schedule(function()
                        completion.clear()
                        state.completions_cache = nil
                end)
        end, { expr = true })
end

return M
```
What should I fix it?

**Comment by amirbilu** [comment]
Hi @Yang-Kyle I assume your Neovim version is < 0.7? If so - an upgrade should fix this

**Comment by aarondill** [comment]
@amirbilu This issue can be closed, as it's just a versioning issue. Please take a look at my patch in #79 to resolve this issue for future users! :smile:

**Comment by Yang-Kyle** [comment]
@amirbilu  @aarondill
I'm sorry for taking so long to reply, but due to some reasons, the network speed I rely on for updating is very slow.
I love your help !

> I run this to solve it.
```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update && sudo apt-get upgrade && sudo apt-get install neovim
```
