### ISSUE TITLE
No suggestions shown in ssh remote server

### ISSUE THREAD

**Issue by LiYaoYu** [codota/tabnine-nvim#89]
I have a local machine and a remote server, with the same neovim configurations.
tabnine suggestion works great on my local machine, but not on the remote server.
By defining the `log_file_path`, I am able to get the tabnine log and do the comparison between the two machines.
And I found the remote server gets the ERROR as below:
```
ERROR [in_app_messaging::internal] [2023-06-24:23:28:48 TabNine ERROR] Error while fetching messages. reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }
```
Not sure if it causes the fail, is there any idea for this?

**Comment by aarondill** [comment]
Seems like the tabnine binaries aren't providing a response. Are they properly installed and updated *on the remote server*? Try running `dl_binaries.sh` again to see if it potentially fixes the issue.

**Comment by aarondill** [comment]
well, actually, *the binaries* are having an issue getting a response. I'd still try updating them to see if it fixes the issue, but next, I wonder if the remote server has an open connection to the internet?

**Comment by LiYaoYu** [comment]
Thanks for the response!
I tried to run `dl_binaries.sh` again manually, and it doesn't work.
And yes, the remote server has full access to the internet.
As you mentioned, it means that there're existing issues for binaries to handle the response?
By the way, the output of `tree .` in the tabnine-nvim directory is as below, not sure if it helps.

```
.
├── binaries
│   └── 4.5.9
│       └── x86_64-unknown-linux-musl
│           ├── TabNine
│           ├── TabNine-deep-cloud
│           ├── TabNine-deep-local
│           └── WD-TabNine
├── dl_binaries.ps1
├── dl_binaries.sh
├── doc
│   ├── tabnine.txt
│   └── tags
├── examples
│   ├── javascript.gif
│   ├── javascript.js
│   └── python.py
├── lua
│   ├── lualine
│   │   └── components
│   │       └── tabnine.lua
│   ├── tabnine
│   │   ├── auto_commands.lua
│   │   ├── binary.lua
│   │   ├── completion.lua
│   │   ├── config.lua
│   │   ├── consts.lua
│   │   ├── keymaps.lua
│   │   ├── state.lua
│   │   ├── status.lua
│   │   ├── third_party
│   │   │   └── semver
│   │   │       ├── MIT-LICENSE.txt
│   │   │       ├── README.md
│   │   │       ├── rockspecs
│   │   │       │   ├── semver-1.1.0-1.rockspec
│   │   │       │   ├── semver-1.1.1-1.rockspec
│   │   │       │   ├── semver-1.2.0-1.rockspec
│   │   │       │   └── semver-1.2.1-1.rockspec
│   │   │       ├── semver.lua
│   │   │       └── spec
│   │   │           ├── custom_assertions.lua
│   │   │           └── semver_spec.lua
│   │   ├── user_commands.lua
│   │   └── utils.lua
│   └── tabnine.lua
└── README.md
```

**Comment by aarondill** [comment]
it appears that somewhere the binaries are receiving an empty JSON request, causing them to error. sadly, the tabnine binaries are closed source, so I don't know if this is an issue with neovim, your internet, or a bug in the binaries.

Someone from the team, such as @amirbilu will need to respond to continue trying to fix this, sorry

**Comment by LiYaoYu** [comment]
It's ok, thank you for the help!
If there's any way to run the binaries directly without Neovim to check the behavior, please let me know, thank you!

**Comment by amirbilu** [comment]
Hi @LiYaoYu is this still happening?

**Comment by amirbilu** [comment]
closing this for now. Feel free to reopen.
