### ISSUE TITLE
Feature: Disallow completion in specific buffer types

### ISSUE THREAD

**Issue by bmalinconico** [codota/tabnine-nvim#9]
I'm getting virtual text in buffer types which are inappropriate for completion. For example in the Telescope prompt 
![image](https://user-images.githubusercontent.com/19909708/211021752-bbe4de15-b939-4845-a962-9d473ca98f54.png) (Note: I've typed `table` so far)

You can identify these prompts by their filetype, in this case the value is `TelescopePrompt`

I would propose adding a config option of buffer types to exclude from virtual text.

**Comment by amirbilu** [comment]
Hi @bmalinconico 
Thanks for reaching out!!

I've Just issued this quick PR https://github.com/codota/tabnine-nvim/pull/11 let me know of what you think

**Comment by amirbilu** [comment]
Closing this as resolved.  Thanks for submitting this!
