### ISSUE TITLE
[BUG] [1]+  Stopped                 nvim src/path/to/1.ts

### ISSUE THREAD

**Issue by kalloc** [codota/tabnine-nvim#91]
**Describe the bug**
Vim with last tabnine continuously stopped with HUP signal. 

**To Reproduce**

1. open any file
2. switch to edit mode
3. [1]+  Stopped                 nvim src/app.module.ts 

**Version Info:**

- OS Ubuntu 22.04.2 LTS
- Neovim version v0.8.1
- Installed Tabnine Binaries (`4.5.10`):

**Comment by aarondill** [comment]
I think this might be an issue with another plugin or configuration.

Is your nvim config available on the internet? 

How are you starting nvim? what is `src/path/to/1.ts`? is that one of your personal files or a file from an nvim plugin? Tabnine has no TypeScript in its source, so if it an issue with that specific file, it's not us.

Please try disabling the `tabnine-nvim` plugin and attempt to reproduce the issue

**Comment by amirbilu** [comment]
Hi @kalloc is this is still happening?

**Comment by QuackBooster** [comment]
Hi, Im seeing the same issue and "same solution" ,  just removed the tabnine-nvim plugin and the issue fixed.

* Fedora 39 with kernel 6.7.1-0.rc1.250.vanilla.fc39.x86_64
* Wayland
* Neovim v0.10.0-dev-2164+gdc466f9a6 ( upstream ) 

You can see the full neovim dotfile at
https://github.com/QuackBooster/super-machine-setup/blob/next/vim/init.vim



> @aarondill `src/path/to/1.ts` is just any file in my workspace, personal file. I tried to disable the `tabnine-nvim` and everything works well. I can try with an empty setup with only tabnine installed. Also, I'm working in ssh (remote shell) on a server without any UI.

**Comment by aarondill** [comment]
@QuackBooster can you reproduce this with *just* tabnine installed?

<details>
<summary>init.vim</summary>

```vimscript

" VIM PLUG AUTOMATIC INSTALLATION
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" TABNINE

" BEGIN
call plug#begin('~/.local/share/nvim/plugged')

Plug 'codota/tabnine-nvim', { 'do': './dl_binaries.sh' }

call plug#end()

lua <<EOF

-- tabnine
require('tabnine').setup({
  disable_auto_comment=true,
  accept_keymap="<C-space>",
  dismiss_keymap = "<C-]>",
  debounce_ms = 800,
  suggestion_color = {gui = "#808080", cterm = 244},
  exclude_filetypes = {"TelescopePrompt", "NvimTree"},
  log_file_path = nil, -- absolute path to Tabnine log file
})

EOF

```

</details>

**Comment by QuackBooster** [comment]
Hi, i reinstall all things from scratch and everything works well. I think is something related to `coc.nvim` extensions, saw some logs in the troubleshooting "autocomplete code" issues.  Not sure if is tss server ...

Using the latest
https://github.com/QuackBooster/super-machine-setup/blob/next/vim/init.vim

coc.nvim 
https://github.com/QuackBooster/super-machine-setup/blob/next/vim/package.json

I think we could close this issue, agreed @kalloc  ?

**Comment by kalloc** [comment]
Let me try the fix. Sorry , I didn't read notifications.

**Comment by QuackBooster** [comment]
Cool, the life gets better with a set proper github notifications!

**Comment by aarondill** [comment]
@kalloc did that fix your issue?

**Comment by kalloc** [comment]
solved! thanks !
