### ISSUE TITLE
[BUG] Chat Install with Cargo fails

### ISSUE THREAD

**Issue by aemonge** [codota/tabnine-nvim#96]
**Describe the bug**
Install fails with this error:
```
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "javascriptcoregtk-4.1" "javas
criptcoregtk-4.1 >= 2.38"` did not exit successfully: exit status: 1
  error: could not find system library 'javascriptcoregtk-4.1' required by the 'javascriptcore-rs-sys' crate

  --- stderr
  Package javascriptcoregtk-4.1 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `javascriptcoregtk-4.1.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'javascriptcoregtk-4.1', required by 'virtual:world', not found
  Package 'javascriptcoregtk-4.1', required by 'virtual:world', not found
```

**To Reproduce**
Version:
```
❯ rustc --version
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

1. `cd ~/.local/share/nvim/lazy/tabnine-nvim/chat`
2. `cargo build --release`

**Expected behavior**

**Version Info:**

- OS (try `cat /etc/os-release`):
❯ cat /etc/os-release
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
BUILD_ID=20230508.1
VERSION_ID=3.4.8

- Neovim version (`nvim -v`):
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`):
❯ ls -A binaries
4.5.24

**Comment by aarondill** [comment]
You're missing the system library `javascriptcoregtk-4.1`.
On Ubuntu this is in the package `libjavascriptcoregtk-4.1-dev`, on arch, I *think* it's in the `javascriptcoregtk-4.1` package, if you're using another disto, just Google your disto and the name of the library

**Comment by aemonge** [comment]
It has been built!  

But, I can't see it nor open it:
```
:TabnineChat<cr>
>>> Nothing happens
:TabnineChatNew
>>> 2023-07-27T11:59:07  WARN tabnine chat not found, did you remember to start it first?
```

I did got access to the chat-alpha, through email

**Comment by aemonge** [comment]
As a reference to any other *arch*ie it's:
```
pacman -S webkit2gtk-4.1
```

**Comment by aarondill** [comment]
Just to cover all the bases, are you running this in a DE/WM? Ie, are you capable of displaying *visual windows*?

**Comment by aemonge** [comment]
KDE Plasma, with Konsole

**Comment by aemonge** [comment]
New output:
```
2023-07-31T12:31:28  WARN Something went wrong running Tabnine chat (signal 5)
```

**Comment by aarondill** [comment]
Signal 5 is `SIGTRAP`. That's extremely unusual. @amirbilu do you have any idea what's going on here?

**Comment by aarondill** [comment]
This could also be exit 133? since exit codes over 128 are generally interpreted as a signal

**Comment by aarondill** [comment]
could you please post the output of this:
```shell
> ~/.local/share/nvim/lazy/tabnine-nvim/chat/target/release/tabnine_chat; echo "Exit: $?"
```

**Comment by aemonge** [comment]
Sure:
```
❯ ~/.local/share/nvim/lazy/tabnine-nvim/chat/target/release/tabnine_chat; echo "Exit: $?"
Exit: 0
```

**Comment by aarondill** [comment]
Please try applying this patch([patch.txt](https://github.com/codota/tabnine-nvim/files/12227305/patch.txt)) and posting the output after running `:TabnineChat`.

Note: there will likely be a *lot* of output. 
Note: there will almost definitely be identifying information and/or access tokens (to access your github avatar). I *highly* recommend checking the output for any of this information and censoring it.

**Comment by aemonge** [comment]
```
❯ git st
HEAD detached at 1837949
nothing to commit, working tree clean
❯ git apply ~/desktop/patch.txt
❯ git st
HEAD detached at 1837949
nothing to commit, working tree clean
❯ ./src/main.rs asset-manifest.json
❯ ./target/release/tabnine_chat
```

And no log when `:TabnineChat`, I've turned off most of my plugins leaving only:
```
  Loaded (4)
    ● lazy.nvim 6.06ms   init.lua
    ● project.nvim 6.16ms  start
    ● tabnine-nvim 6.25ms   javascript
    ● which-key.nvim 3.17ms  start
```

**Comment by aemonge** [comment]
Okey, I think we have advanced:
```
Tabnine Chat is available only for preview users
```

I though, due to the email I was a preview user.


I had to run it with my which-key:
```
            c = { require("tabnine.chat").open, "Chat with tabnine"}
```

Since `:TabnineChat` provided no ouptut.

**Comment by aarondill** [comment]
```shell
> git apply ~/desktop/patch.txt
> git st
HEAD detached at 1837949
nothing to commit, working tree clean
```

This shouldn't say nothing to commit. This should say
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   lua/tabnine/chat/binary.lua

no changes added to commit (use "git add" and/or "git commit -a")
```

Would you mind double checking the patch downloaded correctly with `cat ~/desktop/patch.txt`?

**Comment by aemonge** [comment]
```
❯ cat ~/desktop/patch.txt
diff --git a/lua/tabnine/chat/binary.lua b/lua/tabnine/chat/binary.lua
index 08ff044..35e4d86 100644
--- a/lua/tabnine/chat/binary.lua
+++ b/lua/tabnine/chat/binary.lua
@@ -67,6 +67,7 @@ function ChatBinary:start()
                if chunk then
                        for _, line in pairs(utils.str_to_lines(chunk)) do
                                local message = vim.json.decode(line)
+                               vim.notify("From program: \n" .. vim.inspect(message))
                                local handler = self.registry[message.command]
                                if handler then
                                        handler(message.data, function(payload)
@@ -102,6 +103,7 @@ end
 
 function ChatBinary:post_message(message)
        if self.stdin then
+               vim.notify("To program:\n" .. vim.inspect(message))
                uv.write(self.stdin, json.encode(message) .. "\n")
        else
                vim.notify("tabnine chat not found, did you remember to start it first?", vim.log.levels.WARN)
❯ git apply ~/desktop/patch.txt
```

**Comment by aarondill** [comment]
> Okey, I think we have advanced:
> 
> ```
> Tabnine Chat is available only for preview users
> ```
> 
> I though, due to the email I was a preview user.
> 
> I had to run it with my which-key:
> 
> ```
>             c = { require("tabnine.chat").open, "Chat with tabnine"}
> ```
> 
> Since `:TabnineChat` provided no ouptut.

well, that seems promising at least. I wonder why :TabnineChat didn't show that output though

**Comment by aarondill** [comment]
Plus, the Tabnine Chat should've never started if you weren't in the preview (thusly avoiding the`WARN Something went wrong running Tabnine chat (signal 5)`)

**Comment by aarondill** [comment]
I must say, I'm confused here. Let me know if joining the preview fixes the problem...

**Comment by aemonge** [comment]
I am happy to keep debugging with you, just let me know what to execute ;)

I've just emailed join the enabled list, and will let you know.

**Comment by aemonge** [comment]
It's working !!!

As a suggestion, would be nice to have it interfaced it in vim, or at least readinput `set mode vi`. 

Anyhow, I'm keen to move my conversation from chatGPT towards tabnine-chat :)

**Comment by aarondill** [comment]
> As a suggestion, would be nice to have it interfaced it in vim, or at least readinput `set mode vi`. 

Sadly, the Tabnine chat is developed in a separate (private) repo, so while I would also love this feature, this isn't the right place for feature requests. The best I can offer is #92, or else send an email to the support team?

**Comment by aemonge** [comment]
Done :wink:  https://github.com/codota/tabnine-nvim/issues/92#issuecomment-1661654113
